//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACarValRLC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACarValRLC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstrumentName" type="{http://www.example.com/tse/TSETypes}LVal18"/>
 *         &lt;element name="Type" type="{http://www.example.com/tse/TSETypes}YVal"/>
 *         &lt;element name="Filler10" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="CodeOfCountry" type="{http://www.example.com/tse/TSETypes}CPyEmet"/>
 *         &lt;element name="AmountOfParValue" type="{http://www.example.com/tse/TSETypes}QNmVlo"/>
 *         &lt;element name="Filler03" type="{http://www.example.com/tse/TSETypes}Filler_3"/>
 *         &lt;element name="NumberOfSharesOrBonds" type="{http://www.example.com/tse/TSETypes}ZTitAd"/>
 *         &lt;element name="CodeForIssuingCompany" type="{http://www.example.com/tse/TSETypes}CSocCSAC"/>
 *         &lt;element name="AFCName" type="{http://www.example.com/tse/TSETypes}LSoc30"/>
 *         &lt;element name="FillerC6" type="{http://www.example.com/tse/TSETypes}Filler_6"/>
 *         &lt;element name="FillerC3" type="{http://www.example.com/tse/TSETypes}Filler_3"/>
 *         &lt;element name="FillerC9" type="{http://www.example.com/tse/TSETypes}Filler_9"/>
 *         &lt;element name="FillerC2" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *         &lt;element name="FillerC13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="FillerC1" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerC32" type="{http://www.example.com/tse/TSETypes}Filler_32"/>
 *         &lt;element name="DateOfChangeTakeEffect" type="{http://www.example.com/tse/TSETypes}DESop"/>
 *         &lt;element name="TypeOfCorporateEvent" type="{http://www.example.com/tse/TSETypes}YOPSJ"/>
 *         &lt;element name="CodeOfInstrumentCategory" type="{http://www.example.com/tse/TSETypes}CGdSVal"/>
 *         &lt;element name="Filler7" type="{http://www.example.com/tse/TSETypes}Filler_7"/>
 *         &lt;element name="CurrencyCodeForIssuePrice" type="{http://www.example.com/tse/TSETypes}CDevPEmis"/>
 *         &lt;element name="IssuePrice" type="{http://www.example.com/tse/TSETypes}PEmis"/>
 *         &lt;element name="Filler2" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *         &lt;element name="Filler1C" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="Filler11" type="{http://www.example.com/tse/TSETypes}Filler_11"/>
 *         &lt;element name="VWAPSecurityFlag" type="{http://www.example.com/tse/TSETypes}ILcoVwap"/>
 *         &lt;element name="GroupId" type="{http://www.example.com/tse/TSETypes}CGrValCot"/>
 *         &lt;element name="Filler3" type="{http://www.example.com/tse/TSETypes}Filler_3"/>
 *         &lt;element name="Filler12C" type="{http://www.example.com/tse/TSETypes}Filler_12"/>
 *         &lt;element name="CountryCodeListed" type="{http://www.example.com/tse/TSETypes}CPyCot"/>
 *         &lt;element name="CurrencyCode" type="{http://www.example.com/tse/TSETypes}CDevCot"/>
 *         &lt;element name="DateOfFirstDay" type="{http://www.example.com/tse/TSETypes}DInMar"/>
 *         &lt;element name="SegmentForSecurity" type="{http://www.example.com/tse/TSETypes}CCpmLco"/>
 *         &lt;element name="Filler6" type="{http://www.example.com/tse/TSETypes}Filler_6"/>
 *         &lt;element name="SetOfVariablePrice" type="{http://www.example.com/tse/TSETypes}CIdxPasCotVarVal"/>
 *         &lt;element name="TypeOfUnit" type="{http://www.example.com/tse/TSETypes}YUniExpP"/>
 *         &lt;element name="DateOfLastPrice" type="{http://www.example.com/tse/TSETypes}DDrCV"/>
 *         &lt;element name="LastAdjustedAndSuper" type="{http://www.example.com/tse/TSETypes}PDrAjSajCotV"/>
 *         &lt;element name="Filler013" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="LastAdjustedClosingPrice" type="{http://www.example.com/tse/TSETypes}PDrAjCotV"/>
 *         &lt;element name="AmountOfPriceTick" type="{http://www.example.com/tse/TSETypes}QPasCotFxeVal"/>
 *         &lt;element name="AFCName18" type="{http://www.example.com/tse/TSETypes}LVal18AFC"/>
 *         &lt;element name="FillerD1" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerD01" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerD2" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *         &lt;element name="FillerD02" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *         &lt;element name="Filler13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="CashProductCodeMessageSent" type="{http://www.example.com/tse/TSETypes}CAFCValObjMsg"/>
 *         &lt;element name="Filler28" type="{http://www.example.com/tse/TSETypes}Filler_28"/>
 *         &lt;element name="FillerF5" type="{http://www.example.com/tse/TSETypes}Filler_5"/>
 *         &lt;element name="FillerF01" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerF13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="FillerF2" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *         &lt;element name="FillerF1" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="LotSize" type="{http://www.example.com/tse/TSETypes}QQtTranMarVal"/>
 *         &lt;element name="FillerG1" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerG8" type="{http://www.example.com/tse/TSETypes}Filler_8"/>
 *         &lt;element name="Name30" type="{http://www.example.com/tse/TSETypes}LVal30"/>
 *         &lt;element name="FillerL6" type="{http://www.example.com/tse/TSETypes}Filler_6"/>
 *         &lt;element name="FillerL8" type="{http://www.example.com/tse/TSETypes}Filler_8"/>
 *         &lt;element name="FillerL7" type="{http://www.example.com/tse/TSETypes}Filler_7"/>
 *         &lt;element name="IsinCode" type="{http://www.example.com/tse/TSETypes}CIsin"/>
 *         &lt;element name="FillerH18" type="{http://www.example.com/tse/TSETypes}Filler_18"/>
 *         &lt;element name="FillerH17" type="{http://www.example.com/tse/TSETypes}Filler_17"/>
 *         &lt;element name="FillerH13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="WeightedAverageSpreadQuantity" type="{http://www.example.com/tse/TSETypes}ZNorTitBlcNg"/>
 *         &lt;element name="FillerG01" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerG13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="FillerG11" type="{http://www.example.com/tse/TSETypes}Filler_11"/>
 *         &lt;element name="MarketFlowCode" type="{http://www.example.com/tse/TSETypes}CFlmVal"/>
 *         &lt;element name="FillerJ1" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerJ130" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="FillerJ3" type="{http://www.example.com/tse/TSETypes}Filler_3"/>
 *         &lt;element name="FillerJ12" type="{http://www.example.com/tse/TSETypes}Filler_12"/>
 *         &lt;element name="FillerJ01" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerJ13" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *         &lt;element name="FillerJ001" type="{http://www.example.com/tse/TSETypes}Filler_1"/>
 *         &lt;element name="FillerJ013" type="{http://www.example.com/tse/TSETypes}Filler_13"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACarValRLC", propOrder = {
    "instrumentName",
    "type",
    "filler10",
    "codeOfCountry",
    "amountOfParValue",
    "filler03",
    "numberOfSharesOrBonds",
    "codeForIssuingCompany",
    "afcName",
    "fillerC6",
    "fillerC3",
    "fillerC9",
    "fillerC2",
    "fillerC13",
    "fillerC1",
    "fillerC32",
    "dateOfChangeTakeEffect",
    "typeOfCorporateEvent",
    "codeOfInstrumentCategory",
    "filler7",
    "currencyCodeForIssuePrice",
    "issuePrice",
    "filler2",
    "filler1C",
    "filler11",
    "vwapSecurityFlag",
    "groupId",
    "filler3",
    "filler12C",
    "countryCodeListed",
    "currencyCode",
    "dateOfFirstDay",
    "segmentForSecurity",
    "filler6",
    "setOfVariablePrice",
    "typeOfUnit",
    "dateOfLastPrice",
    "lastAdjustedAndSuper",
    "filler013",
    "lastAdjustedClosingPrice",
    "amountOfPriceTick",
    "afcName18",
    "fillerD1",
    "fillerD01",
    "fillerD2",
    "fillerD02",
    "filler13",
    "cashProductCodeMessageSent",
    "filler28",
    "fillerF5",
    "fillerF01",
    "fillerF13",
    "fillerF2",
    "fillerF1",
    "lotSize",
    "fillerG1",
    "fillerG8",
    "name30",
    "fillerL6",
    "fillerL8",
    "fillerL7",
    "isinCode",
    "fillerH18",
    "fillerH17",
    "fillerH13",
    "weightedAverageSpreadQuantity",
    "fillerG01",
    "fillerG13",
    "fillerG11",
    "marketFlowCode",
    "fillerJ1",
    "fillerJ130",
    "fillerJ3",
    "fillerJ12",
    "fillerJ01",
    "fillerJ13",
    "fillerJ001",
    "fillerJ013"
})
public class ACarValRLC {

    @XmlElement(name = "InstrumentName", required = true)
    protected String instrumentName;
    @XmlElement(name = "Type", required = true)
    protected BigInteger type;
    @XmlElement(name = "Filler10", required = true)
    protected String filler10;
    @XmlElement(name = "CodeOfCountry", required = true)
    protected String codeOfCountry;
    @XmlElement(name = "AmountOfParValue", required = true)
    protected QNmVlo amountOfParValue;
    @XmlElement(name = "Filler03", required = true)
    protected String filler03;
    @XmlElement(name = "NumberOfSharesOrBonds", required = true)
    protected BigInteger numberOfSharesOrBonds;
    @XmlElement(name = "CodeForIssuingCompany", required = true)
    protected String codeForIssuingCompany;
    @XmlElement(name = "AFCName", required = true)
    protected String afcName;
    @XmlElement(name = "FillerC6", required = true)
    protected String fillerC6;
    @XmlElement(name = "FillerC3", required = true)
    protected String fillerC3;
    @XmlElement(name = "FillerC9", required = true)
    protected String fillerC9;
    @XmlElement(name = "FillerC2", required = true)
    protected BigInteger fillerC2;
    @XmlElement(name = "FillerC13", required = true)
    protected String fillerC13;
    @XmlElement(name = "FillerC1", required = true)
    protected String fillerC1;
    @XmlElement(name = "FillerC32", required = true)
    protected String fillerC32;
    @XmlElement(name = "DateOfChangeTakeEffect", required = true)
    protected String dateOfChangeTakeEffect;
    @XmlElement(name = "TypeOfCorporateEvent", required = true)
    protected String typeOfCorporateEvent;
    @XmlElement(name = "CodeOfInstrumentCategory", required = true)
    @XmlSchemaType(name = "string")
    protected CGdSVal codeOfInstrumentCategory;
    @XmlElement(name = "Filler7", required = true)
    protected String filler7;
    @XmlElement(name = "CurrencyCodeForIssuePrice", required = true)
    protected String currencyCodeForIssuePrice;
    @XmlElement(name = "IssuePrice", required = true)
    protected PEmis issuePrice;
    @XmlElement(name = "Filler2", required = true)
    protected BigInteger filler2;
    @XmlElement(name = "Filler1C", required = true)
    protected String filler1C;
    @XmlElement(name = "Filler11", required = true)
    protected String filler11;
    @XmlElement(name = "VWAPSecurityFlag", required = true)
    protected String vwapSecurityFlag;
    @XmlElement(name = "GroupId", required = true)
    protected String groupId;
    @XmlElement(name = "Filler3", required = true)
    protected String filler3;
    @XmlElement(name = "Filler12C", required = true)
    protected String filler12C;
    @XmlElement(name = "CountryCodeListed", required = true)
    protected String countryCodeListed;
    @XmlElement(name = "CurrencyCode", required = true)
    protected String currencyCode;
    @XmlElement(name = "DateOfFirstDay", required = true)
    protected String dateOfFirstDay;
    @XmlElement(name = "SegmentForSecurity", required = true)
    protected String segmentForSecurity;
    @XmlElement(name = "Filler6", required = true)
    protected String filler6;
    @XmlElement(name = "SetOfVariablePrice", required = true)
    protected String setOfVariablePrice;
    @XmlElement(name = "TypeOfUnit", required = true)
    protected String typeOfUnit;
    @XmlElement(name = "DateOfLastPrice", required = true)
    protected String dateOfLastPrice;
    @XmlElement(name = "LastAdjustedAndSuper", required = true)
    protected PDrAjSajCotV lastAdjustedAndSuper;
    @XmlElement(name = "Filler013", required = true)
    protected String filler013;
    @XmlElement(name = "LastAdjustedClosingPrice", required = true)
    protected PDrAjCotV lastAdjustedClosingPrice;
    @XmlElement(name = "AmountOfPriceTick", required = true)
    protected QPasCotFxeVal amountOfPriceTick;
    @XmlElement(name = "AFCName18", required = true)
    protected String afcName18;
    @XmlElement(name = "FillerD1", required = true)
    protected String fillerD1;
    @XmlElement(name = "FillerD01", required = true)
    protected String fillerD01;
    @XmlElement(name = "FillerD2", required = true)
    protected BigInteger fillerD2;
    @XmlElement(name = "FillerD02", required = true)
    protected BigInteger fillerD02;
    @XmlElement(name = "Filler13", required = true)
    protected String filler13;
    @XmlElement(name = "CashProductCodeMessageSent", required = true)
    protected BigInteger cashProductCodeMessageSent;
    @XmlElement(name = "Filler28", required = true)
    protected BigInteger filler28;
    @XmlElement(name = "FillerF5", required = true)
    protected String fillerF5;
    @XmlElement(name = "FillerF01", required = true)
    protected String fillerF01;
    @XmlElement(name = "FillerF13", required = true)
    protected String fillerF13;
    @XmlElement(name = "FillerF2", required = true)
    protected BigInteger fillerF2;
    @XmlElement(name = "FillerF1", required = true)
    protected String fillerF1;
    @XmlElement(name = "LotSize", required = true)
    protected BigInteger lotSize;
    @XmlElement(name = "FillerG1", required = true)
    protected String fillerG1;
    @XmlElement(name = "FillerG8", required = true)
    protected BigInteger fillerG8;
    @XmlElement(name = "Name30", required = true)
    protected String name30;
    @XmlElement(name = "FillerL6", required = true)
    protected String fillerL6;
    @XmlElement(name = "FillerL8", required = true)
    protected BigInteger fillerL8;
    @XmlElement(name = "FillerL7", required = true)
    protected String fillerL7;
    @XmlElement(name = "IsinCode", required = true)
    protected String isinCode;
    @XmlElement(name = "FillerH18", required = true)
    protected String fillerH18;
    @XmlElement(name = "FillerH17", required = true)
    protected String fillerH17;
    @XmlElement(name = "FillerH13", required = true)
    protected String fillerH13;
    @XmlElement(name = "WeightedAverageSpreadQuantity", required = true)
    protected BigInteger weightedAverageSpreadQuantity;
    @XmlElement(name = "FillerG01", required = true)
    protected String fillerG01;
    @XmlElement(name = "FillerG13", required = true)
    protected String fillerG13;
    @XmlElement(name = "FillerG11", required = true)
    protected String fillerG11;
    @XmlElement(name = "MarketFlowCode", required = true)
    protected String marketFlowCode;
    @XmlElement(name = "FillerJ1", required = true)
    protected String fillerJ1;
    @XmlElement(name = "FillerJ130", required = true)
    protected String fillerJ130;
    @XmlElement(name = "FillerJ3", required = true)
    protected String fillerJ3;
    @XmlElement(name = "FillerJ12", required = true)
    protected String fillerJ12;
    @XmlElement(name = "FillerJ01", required = true)
    protected String fillerJ01;
    @XmlElement(name = "FillerJ13", required = true)
    protected String fillerJ13;
    @XmlElement(name = "FillerJ001", required = true)
    protected String fillerJ001;
    @XmlElement(name = "FillerJ013", required = true)
    protected String fillerJ013;

    /**
     * Gets the value of the instrumentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentName() {
        return instrumentName;
    }

    /**
     * Sets the value of the instrumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentName(String value) {
        this.instrumentName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the filler10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller10() {
        return filler10;
    }

    /**
     * Sets the value of the filler10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller10(String value) {
        this.filler10 = value;
    }

    /**
     * Gets the value of the codeOfCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeOfCountry() {
        return codeOfCountry;
    }

    /**
     * Sets the value of the codeOfCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeOfCountry(String value) {
        this.codeOfCountry = value;
    }

    /**
     * Gets the value of the amountOfParValue property.
     * 
     * @return
     *     possible object is
     *     {@link QNmVlo }
     *     
     */
    public QNmVlo getAmountOfParValue() {
        return amountOfParValue;
    }

    /**
     * Sets the value of the amountOfParValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link QNmVlo }
     *     
     */
    public void setAmountOfParValue(QNmVlo value) {
        this.amountOfParValue = value;
    }

    /**
     * Gets the value of the filler03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller03() {
        return filler03;
    }

    /**
     * Sets the value of the filler03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller03(String value) {
        this.filler03 = value;
    }

    /**
     * Gets the value of the numberOfSharesOrBonds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSharesOrBonds() {
        return numberOfSharesOrBonds;
    }

    /**
     * Sets the value of the numberOfSharesOrBonds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSharesOrBonds(BigInteger value) {
        this.numberOfSharesOrBonds = value;
    }

    /**
     * Gets the value of the codeForIssuingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeForIssuingCompany() {
        return codeForIssuingCompany;
    }

    /**
     * Sets the value of the codeForIssuingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeForIssuingCompany(String value) {
        this.codeForIssuingCompany = value;
    }

    /**
     * Gets the value of the afcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfcName() {
        return afcName;
    }

    /**
     * Sets the value of the afcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfcName(String value) {
        this.afcName = value;
    }

    /**
     * Gets the value of the fillerC6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC6() {
        return fillerC6;
    }

    /**
     * Sets the value of the fillerC6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC6(String value) {
        this.fillerC6 = value;
    }

    /**
     * Gets the value of the fillerC3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC3() {
        return fillerC3;
    }

    /**
     * Sets the value of the fillerC3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC3(String value) {
        this.fillerC3 = value;
    }

    /**
     * Gets the value of the fillerC9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC9() {
        return fillerC9;
    }

    /**
     * Sets the value of the fillerC9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC9(String value) {
        this.fillerC9 = value;
    }

    /**
     * Gets the value of the fillerC2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerC2() {
        return fillerC2;
    }

    /**
     * Sets the value of the fillerC2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerC2(BigInteger value) {
        this.fillerC2 = value;
    }

    /**
     * Gets the value of the fillerC13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC13() {
        return fillerC13;
    }

    /**
     * Sets the value of the fillerC13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC13(String value) {
        this.fillerC13 = value;
    }

    /**
     * Gets the value of the fillerC1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC1() {
        return fillerC1;
    }

    /**
     * Sets the value of the fillerC1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC1(String value) {
        this.fillerC1 = value;
    }

    /**
     * Gets the value of the fillerC32 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerC32() {
        return fillerC32;
    }

    /**
     * Sets the value of the fillerC32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerC32(String value) {
        this.fillerC32 = value;
    }

    /**
     * Gets the value of the dateOfChangeTakeEffect property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getDateOfChangeTakeEffect() {
        return dateOfChangeTakeEffect;
    }

    /**
     * Sets the value of the dateOfChangeTakeEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateOfChangeTakeEffect(String value) {
        this.dateOfChangeTakeEffect = value;
    }

    /**
     * Gets the value of the typeOfCorporateEvent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getTypeOfCorporateEvent() {
        return typeOfCorporateEvent;
    }

    /**
     * Sets the value of the typeOfCorporateEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeOfCorporateEvent(String value) {
        this.typeOfCorporateEvent = value;
    }

    /**
     * Gets the value of the codeOfInstrumentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CGdSVal }
     *     
     */
    public CGdSVal getCodeOfInstrumentCategory() {
        return codeOfInstrumentCategory;
    }

    /**
     * Sets the value of the codeOfInstrumentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGdSVal }
     *     
     */
    public void setCodeOfInstrumentCategory(CGdSVal value) {
        this.codeOfInstrumentCategory = value;
    }

    /**
     * Gets the value of the filler7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller7() {
        return filler7;
    }

    /**
     * Sets the value of the filler7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller7(String value) {
        this.filler7 = value;
    }

    /**
     * Gets the value of the currencyCodeForIssuePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCodeForIssuePrice() {
        return currencyCodeForIssuePrice;
    }

    /**
     * Sets the value of the currencyCodeForIssuePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCodeForIssuePrice(String value) {
        this.currencyCodeForIssuePrice = value;
    }

    /**
     * Gets the value of the issuePrice property.
     * 
     * @return
     *     possible object is
     *     {@link PEmis }
     *     
     */
    public PEmis getIssuePrice() {
        return issuePrice;
    }

    /**
     * Sets the value of the issuePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PEmis }
     *     
     */
    public void setIssuePrice(PEmis value) {
        this.issuePrice = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFiller2(BigInteger value) {
        this.filler2 = value;
    }

    /**
     * Gets the value of the filler1C property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller1C() {
        return filler1C;
    }

    /**
     * Sets the value of the filler1C property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller1C(String value) {
        this.filler1C = value;
    }

    /**
     * Gets the value of the filler11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller11() {
        return filler11;
    }

    /**
     * Sets the value of the filler11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller11(String value) {
        this.filler11 = value;
    }

    /**
     * Gets the value of the vwapSecurityFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVWAPSecurityFlag() {
        return vwapSecurityFlag;
    }

    /**
     * Sets the value of the vwapSecurityFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVWAPSecurityFlag(String value) {
        this.vwapSecurityFlag = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the filler3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller3() {
        return filler3;
    }

    /**
     * Sets the value of the filler3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller3(String value) {
        this.filler3 = value;
    }

    /**
     * Gets the value of the filler12C property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller12C() {
        return filler12C;
    }

    /**
     * Sets the value of the filler12C property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller12C(String value) {
        this.filler12C = value;
    }

    /**
     * Gets the value of the countryCodeListed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCodeListed() {
        return countryCodeListed;
    }

    /**
     * Sets the value of the countryCodeListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCodeListed(String value) {
        this.countryCodeListed = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the dateOfFirstDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getDateOfFirstDay() {
        return dateOfFirstDay;
    }

    /**
     * Sets the value of the dateOfFirstDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateOfFirstDay(String value) {
        this.dateOfFirstDay = value;
    }

    /**
     * Gets the value of the segmentForSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentForSecurity() {
        return segmentForSecurity;
    }

    /**
     * Sets the value of the segmentForSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentForSecurity(String value) {
        this.segmentForSecurity = value;
    }

    /**
     * Gets the value of the filler6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller6() {
        return filler6;
    }

    /**
     * Sets the value of the filler6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller6(String value) {
        this.filler6 = value;
    }

    /**
     * Gets the value of the setOfVariablePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetOfVariablePrice() {
        return setOfVariablePrice;
    }

    /**
     * Sets the value of the setOfVariablePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetOfVariablePrice(String value) {
        this.setOfVariablePrice = value;
    }

    /**
     * Gets the value of the typeOfUnit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getTypeOfUnit() {
        return typeOfUnit;
    }

    /**
     * Sets the value of the typeOfUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeOfUnit(String value) {
        this.typeOfUnit = value;
    }

    /**
     * Gets the value of the dateOfLastPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getDateOfLastPrice() {
        return dateOfLastPrice;
    }

    /**
     * Sets the value of the dateOfLastPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateOfLastPrice(String value) {
        this.dateOfLastPrice = value;
    }

    /**
     * Gets the value of the lastAdjustedAndSuper property.
     * 
     * @return
     *     possible object is
     *     {@link PDrAjSajCotV }
     *     
     */
    public PDrAjSajCotV getLastAdjustedAndSuper() {
        return lastAdjustedAndSuper;
    }

    /**
     * Sets the value of the lastAdjustedAndSuper property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDrAjSajCotV }
     *     
     */
    public void setLastAdjustedAndSuper(PDrAjSajCotV value) {
        this.lastAdjustedAndSuper = value;
    }

    /**
     * Gets the value of the filler013 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller013() {
        return filler013;
    }

    /**
     * Sets the value of the filler013 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller013(String value) {
        this.filler013 = value;
    }

    /**
     * Gets the value of the lastAdjustedClosingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PDrAjCotV }
     *     
     */
    public PDrAjCotV getLastAdjustedClosingPrice() {
        return lastAdjustedClosingPrice;
    }

    /**
     * Sets the value of the lastAdjustedClosingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDrAjCotV }
     *     
     */
    public void setLastAdjustedClosingPrice(PDrAjCotV value) {
        this.lastAdjustedClosingPrice = value;
    }

    /**
     * Gets the value of the amountOfPriceTick property.
     * 
     * @return
     *     possible object is
     *     {@link QPasCotFxeVal }
     *     
     */
    public QPasCotFxeVal getAmountOfPriceTick() {
        return amountOfPriceTick;
    }

    /**
     * Sets the value of the amountOfPriceTick property.
     * 
     * @param value
     *     allowed object is
     *     {@link QPasCotFxeVal }
     *     
     */
    public void setAmountOfPriceTick(QPasCotFxeVal value) {
        this.amountOfPriceTick = value;
    }

    /**
     * Gets the value of the afcName18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfcName18() {
        return afcName18;
    }

    /**
     * Sets the value of the afcName18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfcName18(String value) {
        this.afcName18 = value;
    }

    /**
     * Gets the value of the fillerD1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerD1() {
        return fillerD1;
    }

    /**
     * Sets the value of the fillerD1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerD1(String value) {
        this.fillerD1 = value;
    }

    /**
     * Gets the value of the fillerD01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerD01() {
        return fillerD01;
    }

    /**
     * Sets the value of the fillerD01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerD01(String value) {
        this.fillerD01 = value;
    }

    /**
     * Gets the value of the fillerD2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerD2() {
        return fillerD2;
    }

    /**
     * Sets the value of the fillerD2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerD2(BigInteger value) {
        this.fillerD2 = value;
    }

    /**
     * Gets the value of the fillerD02 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerD02() {
        return fillerD02;
    }

    /**
     * Sets the value of the fillerD02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerD02(BigInteger value) {
        this.fillerD02 = value;
    }

    /**
     * Gets the value of the filler13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller13() {
        return filler13;
    }

    /**
     * Sets the value of the filler13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller13(String value) {
        this.filler13 = value;
    }

    /**
     * Gets the value of the cashProductCodeMessageSent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCashProductCodeMessageSent() {
        return cashProductCodeMessageSent;
    }

    /**
     * Sets the value of the cashProductCodeMessageSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCashProductCodeMessageSent(BigInteger value) {
        this.cashProductCodeMessageSent = value;
    }

    /**
     * Gets the value of the filler28 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFiller28() {
        return filler28;
    }

    /**
     * Sets the value of the filler28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFiller28(BigInteger value) {
        this.filler28 = value;
    }

    /**
     * Gets the value of the fillerF5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerF5() {
        return fillerF5;
    }

    /**
     * Sets the value of the fillerF5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerF5(String value) {
        this.fillerF5 = value;
    }

    /**
     * Gets the value of the fillerF01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerF01() {
        return fillerF01;
    }

    /**
     * Sets the value of the fillerF01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerF01(String value) {
        this.fillerF01 = value;
    }

    /**
     * Gets the value of the fillerF13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerF13() {
        return fillerF13;
    }

    /**
     * Sets the value of the fillerF13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerF13(String value) {
        this.fillerF13 = value;
    }

    /**
     * Gets the value of the fillerF2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerF2() {
        return fillerF2;
    }

    /**
     * Sets the value of the fillerF2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerF2(BigInteger value) {
        this.fillerF2 = value;
    }

    /**
     * Gets the value of the fillerF1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerF1() {
        return fillerF1;
    }

    /**
     * Sets the value of the fillerF1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerF1(String value) {
        this.fillerF1 = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLotSize(BigInteger value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the fillerG1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerG1() {
        return fillerG1;
    }

    /**
     * Sets the value of the fillerG1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerG1(String value) {
        this.fillerG1 = value;
    }

    /**
     * Gets the value of the fillerG8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerG8() {
        return fillerG8;
    }

    /**
     * Sets the value of the fillerG8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerG8(BigInteger value) {
        this.fillerG8 = value;
    }

    /**
     * Gets the value of the name30 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName30() {
        return name30;
    }

    /**
     * Sets the value of the name30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName30(String value) {
        this.name30 = value;
    }

    /**
     * Gets the value of the fillerL6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerL6() {
        return fillerL6;
    }

    /**
     * Sets the value of the fillerL6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerL6(String value) {
        this.fillerL6 = value;
    }

    /**
     * Gets the value of the fillerL8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFillerL8() {
        return fillerL8;
    }

    /**
     * Sets the value of the fillerL8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFillerL8(BigInteger value) {
        this.fillerL8 = value;
    }

    /**
     * Gets the value of the fillerL7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerL7() {
        return fillerL7;
    }

    /**
     * Sets the value of the fillerL7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerL7(String value) {
        this.fillerL7 = value;
    }

    /**
     * Gets the value of the isinCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsinCode() {
        return isinCode;
    }

    /**
     * Sets the value of the isinCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsinCode(String value) {
        this.isinCode = value;
    }

    /**
     * Gets the value of the fillerH18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerH18() {
        return fillerH18;
    }

    /**
     * Sets the value of the fillerH18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerH18(String value) {
        this.fillerH18 = value;
    }

    /**
     * Gets the value of the fillerH17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerH17() {
        return fillerH17;
    }

    /**
     * Sets the value of the fillerH17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerH17(String value) {
        this.fillerH17 = value;
    }

    /**
     * Gets the value of the fillerH13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerH13() {
        return fillerH13;
    }

    /**
     * Sets the value of the fillerH13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerH13(String value) {
        this.fillerH13 = value;
    }

    /**
     * Gets the value of the weightedAverageSpreadQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeightedAverageSpreadQuantity() {
        return weightedAverageSpreadQuantity;
    }

    /**
     * Sets the value of the weightedAverageSpreadQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeightedAverageSpreadQuantity(BigInteger value) {
        this.weightedAverageSpreadQuantity = value;
    }

    /**
     * Gets the value of the fillerG01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerG01() {
        return fillerG01;
    }

    /**
     * Sets the value of the fillerG01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerG01(String value) {
        this.fillerG01 = value;
    }

    /**
     * Gets the value of the fillerG13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerG13() {
        return fillerG13;
    }

    /**
     * Sets the value of the fillerG13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerG13(String value) {
        this.fillerG13 = value;
    }

    /**
     * Gets the value of the fillerG11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerG11() {
        return fillerG11;
    }

    /**
     * Sets the value of the fillerG11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerG11(String value) {
        this.fillerG11 = value;
    }

    /**
     * Gets the value of the marketFlowCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketFlowCode() {
        return marketFlowCode;
    }

    /**
     * Sets the value of the marketFlowCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketFlowCode(String value) {
        this.marketFlowCode = value;
    }

    /**
     * Gets the value of the fillerJ1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ1() {
        return fillerJ1;
    }

    /**
     * Sets the value of the fillerJ1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ1(String value) {
        this.fillerJ1 = value;
    }

    /**
     * Gets the value of the fillerJ130 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ130() {
        return fillerJ130;
    }

    /**
     * Sets the value of the fillerJ130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ130(String value) {
        this.fillerJ130 = value;
    }

    /**
     * Gets the value of the fillerJ3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ3() {
        return fillerJ3;
    }

    /**
     * Sets the value of the fillerJ3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ3(String value) {
        this.fillerJ3 = value;
    }

    /**
     * Gets the value of the fillerJ12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ12() {
        return fillerJ12;
    }

    /**
     * Sets the value of the fillerJ12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ12(String value) {
        this.fillerJ12 = value;
    }

    /**
     * Gets the value of the fillerJ01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ01() {
        return fillerJ01;
    }

    /**
     * Sets the value of the fillerJ01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ01(String value) {
        this.fillerJ01 = value;
    }

    /**
     * Gets the value of the fillerJ13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ13() {
        return fillerJ13;
    }

    /**
     * Sets the value of the fillerJ13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ13(String value) {
        this.fillerJ13 = value;
    }

    /**
     * Gets the value of the fillerJ001 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ001() {
        return fillerJ001;
    }

    /**
     * Sets the value of the fillerJ001 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ001(String value) {
        this.fillerJ001 = value;
    }

    /**
     * Gets the value of the fillerJ013 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillerJ013() {
        return fillerJ013;
    }

    /**
     * Sets the value of the fillerJ013 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillerJ013(String value) {
        this.fillerJ013 = value;
    }

}
