//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AClasCo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AClasCo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumberOfSection" type="{http://www.example.com/tse/TSETypes}NDivCo"/>
 *         &lt;element name="NumberOfHeading" type="{http://www.example.com/tse/TSETypes}NRubCo"/>
 *         &lt;element name="OrderOfAppearance" type="{http://www.example.com/tse/TSETypes}NRubCo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AClasCo", propOrder = {
    "numberOfSection",
    "numberOfHeading",
    "orderOfAppearance"
})
public class AClasCo {

    @XmlElement(name = "NumberOfSection", required = true)
    protected BigInteger numberOfSection;
    @XmlElement(name = "NumberOfHeading", required = true)
    protected BigInteger numberOfHeading;
    @XmlElement(name = "OrderOfAppearance", required = true)
    protected BigInteger orderOfAppearance;

    /**
     * Gets the value of the numberOfSection property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSection() {
        return numberOfSection;
    }

    /**
     * Sets the value of the numberOfSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSection(BigInteger value) {
        this.numberOfSection = value;
    }

    /**
     * Gets the value of the numberOfHeading property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHeading() {
        return numberOfHeading;
    }

    /**
     * Sets the value of the numberOfHeading property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHeading(BigInteger value) {
        this.numberOfHeading = value;
    }

    /**
     * Gets the value of the orderOfAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderOfAppearance() {
        return orderOfAppearance;
    }

    /**
     * Sets the value of the orderOfAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderOfAppearance(BigInteger value) {
        this.orderOfAppearance = value;
    }

}
