//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdonProdCpsTran complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdonProdCpsTran">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnderlyingIdentificationCode" type="{http://www.example.com/tse/TSETypes}CIsinProdCps"/>
 *         &lt;element name="LegRatioAggregate" type="{http://www.example.com/tse/TSETypes}ARaoCps"/>
 *         &lt;element name="TradePriceInstrument" type="{http://www.example.com/tse/TSETypes}PTranProdCps"/>
 *         &lt;element name="TRSTradeNumberInstrument" type="{http://www.example.com/tse/TSETypes}NTranKLProdCps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdonProdCpsTran", propOrder = {
    "underlyingIdentificationCode",
    "legRatioAggregate",
    "tradePriceInstrument",
    "trsTradeNumberInstrument"
})
public class AdonProdCpsTran {

    @XmlElement(name = "UnderlyingIdentificationCode", required = true)
    protected String underlyingIdentificationCode;
    @XmlElement(name = "LegRatioAggregate", required = true)
    protected ARaoCps legRatioAggregate;
    @XmlElement(name = "TradePriceInstrument", required = true)
    protected PTranProdCps tradePriceInstrument;
    @XmlElement(name = "TRSTradeNumberInstrument", required = true)
    protected BigInteger trsTradeNumberInstrument;

    /**
     * Gets the value of the underlyingIdentificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIdentificationCode() {
        return underlyingIdentificationCode;
    }

    /**
     * Sets the value of the underlyingIdentificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIdentificationCode(String value) {
        this.underlyingIdentificationCode = value;
    }

    /**
     * Gets the value of the legRatioAggregate property.
     * 
     * @return
     *     possible object is
     *     {@link ARaoCps }
     *     
     */
    public ARaoCps getLegRatioAggregate() {
        return legRatioAggregate;
    }

    /**
     * Sets the value of the legRatioAggregate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ARaoCps }
     *     
     */
    public void setLegRatioAggregate(ARaoCps value) {
        this.legRatioAggregate = value;
    }

    /**
     * Gets the value of the tradePriceInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link PTranProdCps }
     *     
     */
    public PTranProdCps getTradePriceInstrument() {
        return tradePriceInstrument;
    }

    /**
     * Sets the value of the tradePriceInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link PTranProdCps }
     *     
     */
    public void setTradePriceInstrument(PTranProdCps value) {
        this.tradePriceInstrument = value;
    }

    /**
     * Gets the value of the trsTradeNumberInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTRSTradeNumberInstrument() {
        return trsTradeNumberInstrument;
    }

    /**
     * Sets the value of the trsTradeNumberInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTRSTradeNumberInstrument(BigInteger value) {
        this.trsTradeNumberInstrument = value;
    }

}
