//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdonCompOmAplKL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdonCompOmAplKL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdTraderIssuing" type="{http://www.example.com/tse/TSETypes}CIdNgSai"/>
 *         &lt;element name="OrderOrigin" type="{http://www.example.com/tse/TSETypes}YCpteOM"/>
 *         &lt;element name="ClientAccountNumber" type="{http://www.example.com/tse/TSETypes}NCptePosIptOm"/>
 *         &lt;element name="TraderOrderNumber" type="{http://www.example.com/tse/TSETypes}CIdOmNg"/>
 *         &lt;element name="OrderEntryDateTime" type="{http://www.example.com/tse/TSETypes}DHSaiOmAdf"/>
 *         &lt;element name="BicOfBroker" type="{http://www.example.com/tse/TSETypes}CBIC"/>
 *         &lt;element name="FreeText" type="{http://www.example.com/tse/TSETypes}LSaiOM"/>
 *         &lt;element name="GiveUpBrokerId" type="{http://www.example.com/tse/TSETypes}CIdMbrDestGupOm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdonCompOmAplKL", propOrder = {
    "idTraderIssuing",
    "orderOrigin",
    "clientAccountNumber",
    "traderOrderNumber",
    "orderEntryDateTime",
    "bicOfBroker",
    "freeText",
    "giveUpBrokerId"
})
public class AdonCompOmAplKL {

    @XmlElement(name = "IdTraderIssuing", required = true)
    protected String idTraderIssuing;
    @XmlElement(name = "OrderOrigin", required = true)
    protected String orderOrigin;
    @XmlElement(name = "ClientAccountNumber", required = true)
    protected String clientAccountNumber;
    @XmlElement(name = "TraderOrderNumber", required = true)
    protected String traderOrderNumber;
    @XmlElement(name = "OrderEntryDateTime", required = true)
    protected String orderEntryDateTime;
    @XmlElement(name = "BicOfBroker", required = true)
    protected CBIC bicOfBroker;
    @XmlElement(name = "FreeText", required = true)
    protected String freeText;
    @XmlElement(name = "GiveUpBrokerId", required = true)
    protected String giveUpBrokerId;

    /**
     * Gets the value of the idTraderIssuing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTraderIssuing() {
        return idTraderIssuing;
    }

    /**
     * Sets the value of the idTraderIssuing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTraderIssuing(String value) {
        this.idTraderIssuing = value;
    }

    /**
     * Gets the value of the orderOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderOrigin() {
        return orderOrigin;
    }

    /**
     * Sets the value of the orderOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderOrigin(String value) {
        this.orderOrigin = value;
    }

    /**
     * Gets the value of the clientAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientAccountNumber() {
        return clientAccountNumber;
    }

    /**
     * Sets the value of the clientAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientAccountNumber(String value) {
        this.clientAccountNumber = value;
    }

    /**
     * Gets the value of the traderOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraderOrderNumber() {
        return traderOrderNumber;
    }

    /**
     * Sets the value of the traderOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraderOrderNumber(String value) {
        this.traderOrderNumber = value;
    }

    /**
     * Gets the value of the orderEntryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getOrderEntryDateTime() {
        return orderEntryDateTime;
    }

    /**
     * Sets the value of the orderEntryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderEntryDateTime(String value) {
        this.orderEntryDateTime = value;
    }

    /**
     * Gets the value of the bicOfBroker property.
     * 
     * @return
     *     possible object is
     *     {@link CBIC }
     *     
     */
    public CBIC getBicOfBroker() {
        return bicOfBroker;
    }

    /**
     * Sets the value of the bicOfBroker property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIC }
     *     
     */
    public void setBicOfBroker(CBIC value) {
        this.bicOfBroker = value;
    }

    /**
     * Gets the value of the freeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeText() {
        return freeText;
    }

    /**
     * Sets the value of the freeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeText(String value) {
        this.freeText = value;
    }

    /**
     * Gets the value of the giveUpBrokerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiveUpBrokerId() {
        return giveUpBrokerId;
    }

    /**
     * Sets the value of the giveUpBrokerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiveUpBrokerId(String value) {
        this.giveUpBrokerId = value;
    }

}
