//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEttTchRLCY1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEttTchRLCY1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeOfHeader" type="{http://www.example.com/tse/TSETypes}YTchRLC"/>
 *         &lt;element name="IdOfApplication" type="{http://www.example.com/tse/TSETypes}CEmetRLC"/>
 *         &lt;element name="MessageLength" type="{http://www.example.com/tse/TSETypes}ZOctMsgRLC"/>
 *         &lt;element name="IncomingMessages" type="{http://www.example.com/tse/TSETypes}NMsgInRLC"/>
 *         &lt;element name="OutgoingMessages" type="{http://www.example.com/tse/TSETypes}NMsgOutRLC"/>
 *         &lt;element name="GroupCode" type="{http://www.example.com/tse/TSETypes}CGRLC"/>
 *         &lt;element name="SubGroupCode" type="{http://www.example.com/tse/TSETypes}CSgrRLC"/>
 *         &lt;element name="MessageType" type="{http://www.example.com/tse/TSETypes}YMsgRLC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEttTchRLCY1", propOrder = {
    "typeOfHeader",
    "idOfApplication",
    "messageLength",
    "incomingMessages",
    "outgoingMessages",
    "groupCode",
    "subGroupCode",
    "messageType"
})
public class AEttTchRLCY1 {

    @XmlElement(name = "TypeOfHeader", required = true)
    protected BigInteger typeOfHeader;
    @XmlElement(name = "IdOfApplication", required = true)
    protected BigInteger idOfApplication;
    @XmlElement(name = "MessageLength", required = true)
    protected BigInteger messageLength;
    @XmlElement(name = "IncomingMessages", required = true)
    protected BigInteger incomingMessages;
    @XmlElement(name = "OutgoingMessages", required = true)
    protected BigInteger outgoingMessages;
    @XmlElement(name = "GroupCode", required = true)
    protected String groupCode;
    @XmlElement(name = "SubGroupCode", required = true)
    protected String subGroupCode;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;

    /**
     * Gets the value of the typeOfHeader property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTypeOfHeader() {
        return typeOfHeader;
    }

    /**
     * Sets the value of the typeOfHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTypeOfHeader(BigInteger value) {
        this.typeOfHeader = value;
    }

    /**
     * Gets the value of the idOfApplication property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdOfApplication() {
        return idOfApplication;
    }

    /**
     * Sets the value of the idOfApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdOfApplication(BigInteger value) {
        this.idOfApplication = value;
    }

    /**
     * Gets the value of the messageLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageLength() {
        return messageLength;
    }

    /**
     * Sets the value of the messageLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageLength(BigInteger value) {
        this.messageLength = value;
    }

    /**
     * Gets the value of the incomingMessages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomingMessages() {
        return incomingMessages;
    }

    /**
     * Sets the value of the incomingMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomingMessages(BigInteger value) {
        this.incomingMessages = value;
    }

    /**
     * Gets the value of the outgoingMessages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutgoingMessages() {
        return outgoingMessages;
    }

    /**
     * Sets the value of the outgoingMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutgoingMessages(BigInteger value) {
        this.outgoingMessages = value;
    }

    /**
     * Gets the value of the groupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * Sets the value of the groupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupCode(String value) {
        this.groupCode = value;
    }

    /**
     * Gets the value of the subGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubGroupCode() {
        return subGroupCode;
    }

    /**
     * Sets the value of the subGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubGroupCode(String value) {
        this.subGroupCode = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

}
