//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEttRLCY1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEttRLCY1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TechnicalHeader" type="{http://www.example.com/tse/TSETypes}AEttTchRLCY1"/>
 *         &lt;element name="FunctionalHeader" type="{http://www.example.com/tse/TSETypes}AEttFnlRLCY1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEttRLCY1", propOrder = {
    "technicalHeader",
    "functionalHeader"
})
public class AEttRLCY1 {

    @XmlElement(name = "TechnicalHeader", required = true)
    protected AEttTchRLCY1 technicalHeader;
    @XmlElement(name = "FunctionalHeader", required = true)
    protected AEttFnlRLCY1 functionalHeader;

    /**
     * Gets the value of the technicalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link AEttTchRLCY1 }
     *     
     */
    public AEttTchRLCY1 getTechnicalHeader() {
        return technicalHeader;
    }

    /**
     * Sets the value of the technicalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link AEttTchRLCY1 }
     *     
     */
    public void setTechnicalHeader(AEttTchRLCY1 value) {
        this.technicalHeader = value;
    }

    /**
     * Gets the value of the functionalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link AEttFnlRLCY1 }
     *     
     */
    public AEttFnlRLCY1 getFunctionalHeader() {
        return functionalHeader;
    }

    /**
     * Sets the value of the functionalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link AEttFnlRLCY1 }
     *     
     */
    public void setFunctionalHeader(AEttFnlRLCY1 value) {
        this.functionalHeader = value;
    }

}
