//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AEttFnlRLCY1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AEttFnlRLCY1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstrumentShortId" type="{http://www.example.com/tse/TSETypes}CSicoRGA"/>
 *         &lt;element name="InstrumentMnemonicCode" type="{http://www.example.com/tse/TSETypes}CValMne"/>
 *         &lt;element name="InstrumentMarketPlaceId" type="{http://www.example.com/tse/TSETypes}CPlCot"/>
 *         &lt;element name="EventTimeStamp" type="{http://www.example.com/tse/TSETypes}ADHEvenRLC"/>
 *         &lt;element name="InstrumentIdentification" type="{http://www.example.com/tse/TSETypes}InstrumentID"/>
 *         &lt;element name="MessageType" type="{http://www.example.com/tse/TSETypes}ZOctMsgRLC5"/>
 *         &lt;element name="Filler" type="{http://www.example.com/tse/TSETypes}Filler_73"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AEttFnlRLCY1", propOrder = {
    "instrumentShortId",
    "instrumentMnemonicCode",
    "instrumentMarketPlaceId",
    "eventTimeStamp",
    "instrumentIdentification",
    "messageType",
    "filler"
})
public class AEttFnlRLCY1 {

    @XmlElement(name = "InstrumentShortId", required = true)
    protected String instrumentShortId;
    @XmlElement(name = "InstrumentMnemonicCode", required = true)
    protected String instrumentMnemonicCode;
    @XmlElement(name = "InstrumentMarketPlaceId", required = true)
    protected BigInteger instrumentMarketPlaceId;
    @XmlElement(name = "EventTimeStamp", required = true)
    protected ADHEvenRLC eventTimeStamp;
    @XmlElement(name = "InstrumentIdentification", required = true)
    protected String instrumentIdentification;
    @XmlElement(name = "MessageType", required = true)
    protected BigInteger messageType;
    @XmlElement(name = "Filler", required = true)
    protected String filler;

    /**
     * Gets the value of the instrumentShortId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentShortId() {
        return instrumentShortId;
    }

    /**
     * Sets the value of the instrumentShortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentShortId(String value) {
        this.instrumentShortId = value;
    }

    /**
     * Gets the value of the instrumentMnemonicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentMnemonicCode() {
        return instrumentMnemonicCode;
    }

    /**
     * Sets the value of the instrumentMnemonicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentMnemonicCode(String value) {
        this.instrumentMnemonicCode = value;
    }

    /**
     * Gets the value of the instrumentMarketPlaceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstrumentMarketPlaceId() {
        return instrumentMarketPlaceId;
    }

    /**
     * Sets the value of the instrumentMarketPlaceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstrumentMarketPlaceId(BigInteger value) {
        this.instrumentMarketPlaceId = value;
    }

    /**
     * Gets the value of the eventTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link ADHEvenRLC }
     *     
     */
    public ADHEvenRLC getEventTimeStamp() {
        return eventTimeStamp;
    }

    /**
     * Sets the value of the eventTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADHEvenRLC }
     *     
     */
    public void setEventTimeStamp(ADHEvenRLC value) {
        this.eventTimeStamp = value;
    }

    /**
     * Gets the value of the instrumentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentIdentification() {
        return instrumentIdentification;
    }

    /**
     * Sets the value of the instrumentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentIdentification(String value) {
        this.instrumentIdentification = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageType(BigInteger value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the filler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller() {
        return filler;
    }

    /**
     * Sets the value of the filler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller(String value) {
        this.filler = value;
    }

}
