//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AHPhaGrcSea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AHPhaGrcSea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PhaseCode" type="{http://www.example.com/tse/TSETypes}CPhaCot"/>
 *         &lt;element name="TriggerTime" type="{http://www.example.com/tse/TSETypes}DHDebPhaGrcSea"/>
 *         &lt;element name="PhaseCodeAfterOpening" type="{http://www.example.com/tse/TSETypes}CPhaAutoGrcAprOv"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AHPhaGrcSea", propOrder = {
    "phaseCode",
    "triggerTime",
    "phaseCodeAfterOpening"
})
public class AHPhaGrcSea {

    @XmlElement(name = "PhaseCode", required = true)
    @XmlSchemaType(name = "string")
    protected CPhaCot phaseCode;
    @XmlElement(name = "TriggerTime", required = true)
    protected BigInteger triggerTime;
    @XmlElement(name = "PhaseCodeAfterOpening", required = true)
    protected String phaseCodeAfterOpening;

    /**
     * Gets the value of the phaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link CPhaCot }
     *     
     */
    public CPhaCot getPhaseCode() {
        return phaseCode;
    }

    /**
     * Sets the value of the phaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPhaCot }
     *     
     */
    public void setPhaseCode(CPhaCot value) {
        this.phaseCode = value;
    }

    /**
     * Gets the value of the triggerTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTriggerTime() {
        return triggerTime;
    }

    /**
     * Sets the value of the triggerTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTriggerTime(BigInteger value) {
        this.triggerTime = value;
    }

    /**
     * Gets the value of the phaseCodeAfterOpening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhaseCodeAfterOpening() {
        return phaseCodeAfterOpening;
    }

    /**
     * Sets the value of the phaseCodeAfterOpening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhaseCodeAfterOpening(String value) {
        this.phaseCodeAfterOpening = value;
    }

}
