//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AIdOm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AIdOm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubscriberID" type="{http://www.example.com/tse/TSETypes}CIdAdh"/>
 *         &lt;element name="OrderEntryDate" type="{http://www.example.com/tse/TSETypes}DSaiOm"/>
 *         &lt;element name="OrderSequenceNumber" type="{http://www.example.com/tse/TSETypes}NSeqOm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AIdOm", propOrder = {
    "subscriberID",
    "orderEntryDate",
    "orderSequenceNumber"
})
public class AIdOm {

    @XmlElement(name = "SubscriberID", required = true)
    protected String subscriberID;
    @XmlElement(name = "OrderEntryDate", required = true)
    protected String orderEntryDate;
    @XmlElement(name = "OrderSequenceNumber", required = true)
    protected BigInteger orderSequenceNumber;

    /**
     * Gets the value of the subscriberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberID() {
        return subscriberID;
    }

    /**
     * Sets the value of the subscriberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberID(String value) {
        this.subscriberID = value;
    }

    /**
     * Gets the value of the orderEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getOrderEntryDate() {
        return orderEntryDate;
    }

    /**
     * Sets the value of the orderEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderEntryDate(String value) {
        this.orderEntryDate = value;
    }

    /**
     * Gets the value of the orderSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderSequenceNumber() {
        return orderSequenceNumber;
    }

    /**
     * Sets the value of the orderSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderSequenceNumber(BigInteger value) {
        this.orderSequenceNumber = value;
    }

}
