//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AMeLim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AMeLim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BestBuyLimitQuantity" type="{http://www.example.com/tse/TSETypes}QTitMeDen"/>
 *         &lt;element name="NumberOfOrdersBestBuyLimit" type="{http://www.example.com/tse/TSETypes}ZOrdMeDem"/>
 *         &lt;element name="BestBuyLimitPrice" type="{http://www.example.com/tse/TSETypes}PMeDem"/>
 *         &lt;element name="BestSellLimitPrice" type="{http://www.example.com/tse/TSETypes}PMeOf"/>
 *         &lt;element name="NumberOfOrders" type="{http://www.example.com/tse/TSETypes}ZOrdMeOf"/>
 *         &lt;element name="BestSellLimitQuantity" type="{http://www.example.com/tse/TSETypes}QTitMeOf"/>
 *         &lt;element name="Filler2" type="{http://www.example.com/tse/TSETypes}Filler_2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AMeLim", propOrder = {
    "bestBuyLimitQuantity",
    "numberOfOrdersBestBuyLimit",
    "bestBuyLimitPrice",
    "bestSellLimitPrice",
    "numberOfOrders",
    "bestSellLimitQuantity",
    "filler2"
})
public class AMeLim {

    @XmlElement(name = "BestBuyLimitQuantity", required = true)
    protected BigInteger bestBuyLimitQuantity;
    @XmlElement(name = "NumberOfOrdersBestBuyLimit", required = true)
    protected BigInteger numberOfOrdersBestBuyLimit;
    @XmlElement(name = "BestBuyLimitPrice", required = true)
    protected PMeDem bestBuyLimitPrice;
    @XmlElement(name = "BestSellLimitPrice", required = true)
    protected PMeOf bestSellLimitPrice;
    @XmlElement(name = "NumberOfOrders", required = true)
    protected BigInteger numberOfOrders;
    @XmlElement(name = "BestSellLimitQuantity", required = true)
    protected BigInteger bestSellLimitQuantity;
    @XmlElement(name = "Filler2", required = true)
    protected BigInteger filler2;

    /**
     * Gets the value of the bestBuyLimitQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBestBuyLimitQuantity() {
        return bestBuyLimitQuantity;
    }

    /**
     * Sets the value of the bestBuyLimitQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBestBuyLimitQuantity(BigInteger value) {
        this.bestBuyLimitQuantity = value;
    }

    /**
     * Gets the value of the numberOfOrdersBestBuyLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOrdersBestBuyLimit() {
        return numberOfOrdersBestBuyLimit;
    }

    /**
     * Sets the value of the numberOfOrdersBestBuyLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOrdersBestBuyLimit(BigInteger value) {
        this.numberOfOrdersBestBuyLimit = value;
    }

    /**
     * Gets the value of the bestBuyLimitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PMeDem }
     *     
     */
    public PMeDem getBestBuyLimitPrice() {
        return bestBuyLimitPrice;
    }

    /**
     * Sets the value of the bestBuyLimitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PMeDem }
     *     
     */
    public void setBestBuyLimitPrice(PMeDem value) {
        this.bestBuyLimitPrice = value;
    }

    /**
     * Gets the value of the bestSellLimitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PMeOf }
     *     
     */
    public PMeOf getBestSellLimitPrice() {
        return bestSellLimitPrice;
    }

    /**
     * Sets the value of the bestSellLimitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PMeOf }
     *     
     */
    public void setBestSellLimitPrice(PMeOf value) {
        this.bestSellLimitPrice = value;
    }

    /**
     * Gets the value of the numberOfOrders property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOrders() {
        return numberOfOrders;
    }

    /**
     * Sets the value of the numberOfOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOrders(BigInteger value) {
        this.numberOfOrders = value;
    }

    /**
     * Gets the value of the bestSellLimitQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBestSellLimitQuantity() {
        return bestSellLimitQuantity;
    }

    /**
     * Sets the value of the bestSellLimitQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBestSellLimitQuantity(BigInteger value) {
        this.bestSellLimitQuantity = value;
    }

    /**
     * Gets the value of the filler2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFiller2() {
        return filler2;
    }

    /**
     * Sets the value of the filler2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFiller2(BigInteger value) {
        this.filler2 = value;
    }

}
