//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.26 at 01:15:55 PM IRST 
//


package com.example.trade.tse.message.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CGdsVal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CGdsVal">
 *   &lt;restriction base="{http://www.example.com/tse/TSETypes}BaseString">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="X"/>
 *     &lt;enumeration value="Y"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="D"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CGdsVal")
@XmlEnum
public enum CGdsVal {

    A,
    O,
    F,
    X,
    Y,
    C,
    P,
    D;

    public String value() {
        return name();
    }

    public static CGdsVal fromValue(String v) {
        return valueOf(v);
    }

}
