//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.rlc;

import com.example.trade.tse.message.entity.*;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.trade.tst.rlc.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndOfNscSessionMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/08", "EndOfNscSessionMessage");
    private final static QName _StatOfNscSessionMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/07", "StatOfNscSessionMessage");
    private final static QName _StartOfInstrumentMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/50", "StartOfInstrumentMessage");
    private final static QName _EndOfInstrumentMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/51", "EndOfInstrumentMessage");
    private final static QName _CreationOfInstrumentMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/53", "CreationOfInstrumentMessage");
    private final static QName _BestLimitMessage_QNAME = new QName("http://www.example.com/tse/message/rlc/04", "BestLimitMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.trade.tst.rlc.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RLCMessage }
     * 
     */
    public RLCMessage createRLCMessage() {
        return new RLCMessage();
    }



    /**
     * Create an instance of {@link PTran }
     * 
     */
    public PTran createPTran() {
        return new PTran();
    }

    /**
     * Create an instance of {@link XQVarPJDrPRf }
     * 
     */
    public XQVarPJDrPRf createXQVarPJDrPRf() {
        return new XQVarPJDrPRf();
    }


    /**
     * Create an instance of {@link PPhSeaCotJ }
     * 
     */
    public PPhSeaCotJ createPPhSeaCotJ() {
        return new PPhSeaCotJ();
    }

    /**
     * Create an instance of {@link PPbSeaCotJ }
     * 
     */
    public PPbSeaCotJ createPPbSeaCotJ() {
        return new PPbSeaCotJ();
    }


    /**
     * Create an instance of {@link PObjMsgP }
     * 
     */
    public PObjMsgP createPObjMsgP() {
        return new PObjMsgP();
    }


    /**
     * Create an instance of {@link AMeLim }
     * 
     */
    public AMeLim createAMeLim() {
        return new AMeLim();
    }




    /**
     * Create an instance of {@link QTotCap }
     * 
     */
    public QTotCap createQTotCap() {
        return new QTotCap();
    }

    /**
     * Create an instance of {@link QTotTran }
     * 
     */
    public QTotTran createQTotTran() {
        return new QTotTran();
    }


    /**
     * Create an instance of {@link PClosing }
     * 
     */
    public PClosing createPClosing() {
        return new PClosing();
    }

    /**
     * Create an instance of {@link PClosingNoAdj }
     * 
     */
    public PClosingNoAdj createPClosingNoAdj() {
        return new PClosingNoAdj();
    }

    /**
     * Create an instance of {@link PVWAP }
     * 
     */
    public PVWAP createPVWAP() {
        return new PVWAP();
    }

    /**
     * Create an instance of {@link PVWAPNoAdj }
     * 
     */
    public PVWAPNoAdj createPVWAPNoAdj() {
        return new PVWAPNoAdj();
    }

    /**
     * Create an instance of {@link PDrCotVal }
     * 
     */
    public PDrCotVal createPDrCotVal() {
        return new PDrCotVal();
    }

    /**
     * Create an instance of {@link PDrcotVaLNoAdj }
     * 
     */
    public PDrcotVaLNoAdj createPDrcotVaLNoAdj() {
        return new PDrcotVaLNoAdj();
    }


    /**
     * Create an instance of {@link TextMessage }
     *
     */
    public TextMessage createTextMessage() {
        return new TextMessage();
    }


    /**
     * Create an instance of {@link PTeoOvJ }
     * 
     */
    public PTeoOvJ createPTeoOvJ() {
        return new PTeoOvJ();
    }

    /**
     * Create an instance of {@link PMeLimSimAcVal }
     * 
     */
    public PMeLimSimAcVal createPMeLimSimAcVal() {
        return new PMeLimSimAcVal();
    }

    /**
     * Create an instance of {@link PMeLimSimVtVal }
     * 
     */
    public PMeLimSimVtVal createPMeLimSimVtVal() {
        return new PMeLimSimVtVal();
    }

    /**
     * Create an instance of {@link OpeningSummaryMessage }
     * 
     */
    public OpeningSummaryMessage createOpeningSummaryMessage() {
        return new OpeningSummaryMessage();
    }

    /**
     * Create an instance of {@link PPrCJ }
     * 
     */
    public PPrCJ createPPrCJ() {
        return new PPrCJ();
    }

    /**
     * Create an instance of {@link DrCotJ }
     * 
     */
    public DrCotJ createDrCotJ() {
        return new DrCotJ();
    }


    /**
     * Create an instance of {@link PSGelStaMax }
     * 
     */
    public PSGelStaMax createPSGelStaMax() {
        return new PSGelStaMax();
    }

    /**
     * Create an instance of {@link PSGelStaMin }
     * 
     */
    public PSGelStaMin createPSGelStaMin() {
        return new PSGelStaMin();
    }


    /**
     * Create an instance of {@link AHPhaGrcSea }
     * 
     */
    public AHPhaGrcSea createAHPhaGrcSea() {
        return new AHPhaGrcSea();
    }


    /**
     * Create an instance of {@link ACarValRLC }
     * 
     */
    public ACarValRLC createACarValRLC() {
        return new ACarValRLC();
    }

    /**
     * Create an instance of {@link AKProdCpsProdYCbn }
     * 
     */
    public AKProdCpsProdYCbn createAKProdCpsProdYCbn() {
        return new AKProdCpsProdYCbn();
    }

    /**
     * Create an instance of {@link QTickValMdv }
     * 
     */
    public QTickValMdv createQTickValMdv() {
        return new QTickValMdv();
    }

    /**
     * Create an instance of {@link PExoProdMdv }
     * 
     */
    public PExoProdMdv createPExoProdMdv() {
        return new PExoProdMdv();
    }

    /**
     * Create an instance of {@link PCompValMdv }
     * 
     */
    public PCompValMdv createPCompValMdv() {
        return new PCompValMdv();
    }

    /**
     * Create an instance of {@link PSaiSMaxOkValMdv }
     * 
     */
    public PSaiSMaxOkValMdv createPSaiSMaxOkValMdv() {
        return new PSaiSMaxOkValMdv();
    }

    /**
     * Create an instance of {@link PSaiSMinOkValMdv }
     * 
     */
    public PSaiSMinOkValMdv createPSaiSMinOkValMdv() {
        return new PSaiSMinOkValMdv();
    }

    /**
     * Create an instance of {@link PCpsDrvObl }
     * 
     */
    public PCpsDrvObl createPCpsDrvObl() {
        return new PCpsDrvObl();
    }

    /**
     * Create an instance of {@link XDtaStg }
     * 
     */
    public XDtaStg createXDtaStg() {
        return new XDtaStg();
    }

    /**
     * Create an instance of {@link StSplitAgg }
     * 
     */
    public StSplitAgg createStSplitAgg() {
        return new StSplitAgg();
    }

    /**
     * Create an instance of {@link StDivAgg }
     * 
     */
    public StDivAgg createStDivAgg() {
        return new StDivAgg();
    }


    /**
     * Create an instance of {@link PLimSaiOm }
     * 
     */
    public PLimSaiOm createPLimSaiOm() {
        return new PLimSaiOm();
    }

    /**
     * Create an instance of {@link PAffOm }
     * 
     */
    public PAffOm createPAffOm() {
        return new PAffOm();
    }

    /**
     * Create an instance of {@link AIdOm }
     * 
     */
    public AIdOm createAIdOm() {
        return new AIdOm();
    }

    public POfDemVal createPOfDemVal() {
        return new POfDemVal();
    }


    /**
     * Create an instance of {@link PMeDem }
     * 
     */
    public PMeDem createPMeDem() {
        return new PMeDem();
    }

    /**
     * Create an instance of {@link AdonCompOmAplKL }
     * 
     */
    public AdonCompOmAplKL createAdonCompOmAplKL() {
        return new AdonCompOmAplKL();
    }

    /**
     * Create an instance of {@link PAc }
     * 
     */
    public PAc createPAc() {
        return new PAc();
    }

    /**
     * Create an instance of {@link AEttTchRLCY1 }
     * 
     */
    public AEttTchRLCY1 createAEttTchRLCY1() {
        return new AEttTchRLCY1();
    }

    /**
     * Create an instance of {@link PEmis }
     * 
     */
    public PEmis createPEmis() {
        return new PEmis();
    }

    /**
     * Create an instance of {@link AEttFnlRLCY1 }
     * 
     */
    public AEttFnlRLCY1 createAEttFnlRLCY1() {
        return new AEttFnlRLCY1();
    }

    /**
     * Create an instance of {@link ASecEco }
     * 
     */
    public ASecEco createASecEco() {
        return new ASecEco();
    }

    /**
     * Create an instance of {@link ADHEvenRLC }
     * 
     */
    public ADHEvenRLC createADHEvenRLC() {
        return new ADHEvenRLC();
    }

    /**
     * Create an instance of {@link AEttRLCY1 }
     * 
     */
    public AEttRLCY1 createAEttRLCY1() {
        return new AEttRLCY1();
    }

    /**
     * Create an instance of {@link AClasCo }
     * 
     */
    public AClasCo createAClasCo() {
        return new AClasCo();
    }

    /**
     * Create an instance of {@link AEttRLCY2 }
     * 
     */
    public AEttRLCY2 createAEttRLCY2() {
        return new AEttRLCY2();
    }

    /**
     * Create an instance of {@link AClsEcoFtseSoc }
     * 
     */
    public AClsEcoFtseSoc createAClsEcoFtseSoc() {
        return new AClsEcoFtseSoc();
    }

    /**
     * Create an instance of {@link PMeOf }
     * 
     */
    public PMeOf createPMeOf() {
        return new PMeOf();
    }

    /**
     * Create an instance of {@link CBIC }
     * 
     */
    public CBIC createCBIC() {
        return new CBIC();
    }

    /**
     * Create an instance of {@link QNmVal }
     * 
     */
    public QNmVal createQNmVal() {
        return new QNmVal();
    }

    /**
     * Create an instance of {@link PDrAjSajCotV }
     * 
     */
    public PDrAjSajCotV createPDrAjSajCotV() {
        return new PDrAjSajCotV();
    }

    /**
     * Create an instance of {@link QPasCotFxeVal }
     * 
     */
    public QPasCotFxeVal createQPasCotFxeVal() {
        return new QPasCotFxeVal();
    }

    /**
     * Create an instance of {@link PTranProdCps }
     * 
     */
    public PTranProdCps createPTranProdCps() {
        return new PTranProdCps();
    }

    /**
     * Create an instance of {@link PDchOmStop }
     * 
     */
    public PDchOmStop createPDchOmStop() {
        return new PDchOmStop();
    }

    /**
     * Create an instance of {@link XIntOblRte }
     * 
     */
    public XIntOblRte createXIntOblRte() {
        return new XIntOblRte();
    }

    /**
     * Create an instance of {@link ASbAniVal }
     * 
     */
    public ASbAniVal createASbAniVal() {
        return new ASbAniVal();
    }

    /**
     * Create an instance of {@link PDrAjCotV }
     * 
     */
    public PDrAjCotV createPDrAjCotV() {
        return new PDrAjCotV();
    }

    /**
     * Create an instance of {@link QNmVlo }
     * 
     */
    public QNmVlo createQNmVlo() {
        return new QNmVlo();
    }

    /**
     * Create an instance of {@link ARaoCps }
     * 
     */
    public ARaoCps createARaoCps() {
        return new ARaoCps();
    }

    /**
     * Create an instance of {@link PVt }
     * 
     */
    public PVt createPVt() {
        return new PVt();
    }

    /**
     * Create an instance of {@link QNmMarValVlo }
     * 
     */
    public QNmMarValVlo createQNmMarValVlo() {
        return new QNmMarValVlo();
    }

    /**
     * Create an instance of {@link PDrCotJ }
     * 
     */
    public PDrCotJ createPDrCotJ() {
        return new PDrCotJ();
    }

    /**
     * Create an instance of {@link QNorCpxBlcFmp }
     * 
     */
    public QNorCpxBlcFmp createQNorCpxBlcFmp() {
        return new QNorCpxBlcFmp();
    }

    /**
     * Create an instance of {@link PLimSaiOM }
     * 
     */
    public PLimSaiOM createPLimSaiOM() {
        return new PLimSaiOM();
    }

    /**
     * Create an instance of {@link AdonCompOmApl }
     * 
     */
    public AdonCompOmApl createAdonCompOmApl() {
        return new AdonCompOmApl();
    }

    /**
     * Create an instance of {@link AdonProdCpsTran }
     * 
     */
    public AdonProdCpsTran createAdonProdCpsTran() {
        return new AdonProdCpsTran();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/tse/message/rlc/08", name = "EndOfNscSessionMessage")
    public JAXBElement<String> createEndOfNscSessionMessage(String value) {
        return new JAXBElement<String>(_EndOfNscSessionMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/tse/message/rlc/07", name = "StatOfNscSessionMessage")
    public JAXBElement<String> createStatOfNscSessionMessage(String value) {
        return new JAXBElement<String>(_StatOfNscSessionMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/tse/message/rlc/50", name = "StartOfInstrumentMessage")
    public JAXBElement<String> createStartOfInstrumentMessage(String value) {
        return new JAXBElement<String>(_StartOfInstrumentMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/tse/message/rlc/51", name = "EndOfInstrumentMessage")
    public JAXBElement<String> createEndOfInstrumentMessage(String value) {
        return new JAXBElement<String>(_EndOfInstrumentMessage_QNAME, String.class, null, value);
    }


}
