//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 01:46:59 PM IRDT 
//


package com.example.trade.tse.message.rlc;

import com.example.trade.tse.message.entity.*;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstTradePriceOfTheTradingDay" type="{http://www.example.com/tse/TSETypes}PPrCJ"/>
 *         &lt;element name="LastTradePriceOfTheTradingDay" type="{http://www.example.com/tse/TSETypes}DrCotJ"/>
 *         &lt;element name="HighestTradePriceOfTheTradingDay" type="{http://www.example.com/tse/TSETypes}PPhSeaCotJ"/>
 *         &lt;element name="LowestTradePriceOfTheTradingDay" type="{http://www.example.com/tse/TSETypes}PPbSeaCotJ"/>
 *         &lt;element name="TrendFlag" type="{http://www.example.com/tse/TSETypes}YPOvVal"/>
 *         &lt;element name="TotalTradedQuantityAtOpening" type="{http://www.example.com/tse/TSETypes}QTitNgOvVal"/>
 *         &lt;element name="LastTradePrice" type="{http://www.example.com/tse/TSETypes}ISensVarP"/>
 *         &lt;element name="Filler5" type="{http://www.example.com/tse/TSETypes}Filler_5"/>
 *         &lt;element name="SignOfPrice" type="{http://www.example.com/tse/TSETypes}CSensVarPTranPP"/>
 *         &lt;element name="PercentageOfPrice" type="{http://www.example.com/tse/TSETypes}XQVarPJDrPRf"/>
 *         &lt;element name="Filler" type="{http://www.example.com/tse/TSETypes}Filler_26"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firstTradePriceOfTheTradingDay",
    "lastTradePriceOfTheTradingDay",
    "highestTradePriceOfTheTradingDay",
    "lowestTradePriceOfTheTradingDay",
    "trendFlag",
    "totalTradedQuantityAtOpening",
    "lastTradePrice",
    "filler5",
    "signOfPrice",
    "percentageOfPrice",
    "filler"
})
@XmlRootElement(name = "OpeningSummaryMessage", namespace = "http://www.example.com/tse/message/rlc/32")
public class OpeningSummaryMessage {

    @XmlElement(name = "FirstTradePriceOfTheTradingDay", required = true)
    protected PPrCJ firstTradePriceOfTheTradingDay;
    @XmlElement(name = "LastTradePriceOfTheTradingDay", required = true)
    protected DrCotJ lastTradePriceOfTheTradingDay;
    @XmlElement(name = "HighestTradePriceOfTheTradingDay", required = true)
    protected PPhSeaCotJ highestTradePriceOfTheTradingDay;
    @XmlElement(name = "LowestTradePriceOfTheTradingDay", required = true)
    protected PPbSeaCotJ lowestTradePriceOfTheTradingDay;
    @XmlElement(name = "TrendFlag", required = true)
    protected BigInteger trendFlag;
    @XmlElement(name = "TotalTradedQuantityAtOpening", required = true)
    protected BigInteger totalTradedQuantityAtOpening;
    @XmlElement(name = "LastTradePrice", required = true)
    protected String lastTradePrice;
    @XmlElement(name = "Filler5", required = true)
    protected String filler5;
    @XmlElement(name = "SignOfPrice", required = true)
    protected String signOfPrice;
    @XmlElement(name = "PercentageOfPrice", required = true)
    protected XQVarPJDrPRf percentageOfPrice;
    @XmlElement(name = "Filler", required = true)
    protected String filler;

    /**
     * Gets the value of the firstTradePriceOfTheTradingDay property.
     * 
     * @return
     *     possible object is
     *     {@link PPrCJ }
     *     
     */
    public PPrCJ getFirstTradePriceOfTheTradingDay() {
        return firstTradePriceOfTheTradingDay;
    }

    /**
     * Sets the value of the firstTradePriceOfTheTradingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PPrCJ }
     *     
     */
    public void setFirstTradePriceOfTheTradingDay(PPrCJ value) {
        this.firstTradePriceOfTheTradingDay = value;
    }

    /**
     * Gets the value of the lastTradePriceOfTheTradingDay property.
     * 
     * @return
     *     possible object is
     *     {@link DrCotJ }
     *     
     */
    public DrCotJ getLastTradePriceOfTheTradingDay() {
        return lastTradePriceOfTheTradingDay;
    }

    /**
     * Sets the value of the lastTradePriceOfTheTradingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrCotJ }
     *     
     */
    public void setLastTradePriceOfTheTradingDay(DrCotJ value) {
        this.lastTradePriceOfTheTradingDay = value;
    }

    /**
     * Gets the value of the highestTradePriceOfTheTradingDay property.
     * 
     * @return
     *     possible object is
     *     {@link PPhSeaCotJ }
     *     
     */
    public PPhSeaCotJ getHighestTradePriceOfTheTradingDay() {
        return highestTradePriceOfTheTradingDay;
    }

    /**
     * Sets the value of the highestTradePriceOfTheTradingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PPhSeaCotJ }
     *     
     */
    public void setHighestTradePriceOfTheTradingDay(PPhSeaCotJ value) {
        this.highestTradePriceOfTheTradingDay = value;
    }

    /**
     * Gets the value of the lowestTradePriceOfTheTradingDay property.
     * 
     * @return
     *     possible object is
     *     {@link PPbSeaCotJ }
     *     
     */
    public PPbSeaCotJ getLowestTradePriceOfTheTradingDay() {
        return lowestTradePriceOfTheTradingDay;
    }

    /**
     * Sets the value of the lowestTradePriceOfTheTradingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PPbSeaCotJ }
     *     
     */
    public void setLowestTradePriceOfTheTradingDay(PPbSeaCotJ value) {
        this.lowestTradePriceOfTheTradingDay = value;
    }

    /**
     * Gets the value of the trendFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrendFlag() {
        return trendFlag;
    }

    /**
     * Sets the value of the trendFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrendFlag(BigInteger value) {
        this.trendFlag = value;
    }

    /**
     * Gets the value of the totalTradedQuantityAtOpening property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalTradedQuantityAtOpening() {
        return totalTradedQuantityAtOpening;
    }

    /**
     * Sets the value of the totalTradedQuantityAtOpening property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalTradedQuantityAtOpening(BigInteger value) {
        this.totalTradedQuantityAtOpening = value;
    }

    /**
     * Gets the value of the lastTradePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTradePrice() {
        return lastTradePrice;
    }

    /**
     * Sets the value of the lastTradePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTradePrice(String value) {
        this.lastTradePrice = value;
    }

    /**
     * Gets the value of the filler5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller5() {
        return filler5;
    }

    /**
     * Sets the value of the filler5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller5(String value) {
        this.filler5 = value;
    }

    /**
     * Gets the value of the signOfPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignOfPrice() {
        return signOfPrice;
    }

    /**
     * Sets the value of the signOfPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignOfPrice(String value) {
        this.signOfPrice = value;
    }

    /**
     * Gets the value of the percentageOfPrice property.
     * 
     * @return
     *     possible object is
     *     {@link XQVarPJDrPRf }
     *     
     */
    public XQVarPJDrPRf getPercentageOfPrice() {
        return percentageOfPrice;
    }

    /**
     * Sets the value of the percentageOfPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link XQVarPJDrPRf }
     *     
     */
    public void setPercentageOfPrice(XQVarPJDrPRf value) {
        this.percentageOfPrice = value;
    }

    /**
     * Gets the value of the filler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller() {
        return filler;
    }

    /**
     * Sets the value of the filler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller(String value) {
        this.filler = value;
    }

}
